//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1Client.Assignment1Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Assignment1Reference.IAssignment1Service")]
    public interface IAssignment1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/primeCheck", ReplyAction="http://tempuri.org/IAssignment1Service/primeCheckResponse")]
        string primeCheck(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/primeCheck", ReplyAction="http://tempuri.org/IAssignment1Service/primeCheckResponse")]
        System.Threading.Tasks.Task<string> primeCheckAsync(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssignment1ServiceChannel : Assignment1Client.Assignment1Reference.IAssignment1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment1ServiceClient : System.ServiceModel.ClientBase<Assignment1Client.Assignment1Reference.IAssignment1Service>, Assignment1Client.Assignment1Reference.IAssignment1Service {
        
        public Assignment1ServiceClient() {
        }
        
        public Assignment1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string primeCheck(int number) {
            return base.Channel.primeCheck(number);
        }
        
        public System.Threading.Tasks.Task<string> primeCheckAsync(int number) {
            return base.Channel.primeCheckAsync(number);
        }
    }
}
